"""Add trade_qualifications jsonb to user

Revision ID: dba0374571a1
Revises: e32251aee45f
Create Date: 2026-06-16 14:33:14.857087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba0374571a1'
down_revision: Union[str, Sequence[str], None] = 'e32251aee45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('trade_qualifications', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'trade_qualifications')
    # ### end Alembic commands ###
