import asyncio
import os
import sys
from pathlib import Path

# Add the project root to sys.path so we can import 'app'
sys.path.append(str(Path(__file__).resolve().parent.parent))

from app.core.database import async_session_maker
from app.core.security import get_password_hash
from app.models.all_models import User

async def seed_db():
    print("Starting database seeding...")
    
    # Pre-hashed password for "password123" to save time
    default_password = get_password_hash("password123")
    
    contractors = [
        User(
            email="mike@plumbingpros.com",
            hashed_password=default_password,
            role="contractor",
            full_name="Mike's Plumbing",
            phone="555-0101",
            zip_code="90210",
            country="United States",
            state_or_province="California",
            city="Beverly Hills",
            area="Beverly Hills",
            postal_code="90210",
            latitude=34.0736,
            longitude=-118.4004,
            profession="plumber",
            service_radius_miles=20,
            base_pricing=120.0,
            max_daily_jobs=6,
            working_hours_start="07:00",
            working_hours_end="17:00",
            ai_tone_preference="professional",
            verification_level="gold",
            reputation_score=4.8,
            availability_status="Available",
        ),
        User(
            email="sarah@sparkyelectric.com",
            hashed_password=default_password,
            role="contractor",
            full_name="Sarah the Sparky",
            phone="555-0102",
            zip_code="90211",
            country="United States",
            state_or_province="California",
            city="Beverly Hills",
            area="West Hollywood",
            postal_code="90211",
            latitude=34.0907,
            longitude=-118.3766,
            profession="electrician",
            service_radius_miles=30,
            base_pricing=150.0,
            max_daily_jobs=4,
            working_hours_start="08:00",
            working_hours_end="18:00",
            ai_tone_preference="friendly",
            verification_level="verified pro",
            reputation_score=4.9,
            availability_status="Available",
        ),
        User(
            email="joe@hvacmasters.com",
            hashed_password=default_password,
            role="contractor",
            full_name="Joe's HVAC Masters",
            phone="555-0103",
            zip_code="90212",
            country="United States",
            state_or_province="California",
            city="Beverly Hills",
            area="Beverly Hills",
            postal_code="90212",
            latitude=34.0697,
            longitude=-118.3985,
            profession="hvac",
            service_radius_miles=50,
            base_pricing=85.0,
            max_daily_jobs=8,
            working_hours_start="06:00",
            working_hours_end="20:00",
            ai_tone_preference="direct",
            verification_level="silver",
            reputation_score=4.5,
            availability_status="Available",
        ),
        User(
            email="emily@elitecleaners.com",
            hashed_password=default_password,
            role="contractor",
            full_name="Elite Home Cleaning",
            phone="555-0104",
            zip_code="90210",
            country="United States",
            state_or_province="California",
            city="Beverly Hills",
            area="Beverly Hills",
            postal_code="90210",
            latitude=34.0736,
            longitude=-118.4004,
            profession="cleaner",
            service_radius_miles=15,
            base_pricing=60.0,
            max_daily_jobs=3,
            working_hours_start="09:00",
            working_hours_end="16:00",
            ai_tone_preference="warm and professional",
            verification_level="bronze",
            reputation_score=4.2,
            availability_status="Available",
        ),
        User(
            email="tony@topnotchroofing.com",
            hashed_password=default_password,
            role="contractor",
            full_name="Top Notch Roofing",
            phone="555-0105",
            zip_code="90215",
            country="United States",
            state_or_province="California",
            city="Los Angeles",
            area="Downtown",
            postal_code="90015",
            latitude=34.0407,
            longitude=-118.2468,
            profession="roofer",
            service_radius_miles=40,
            base_pricing=250.0,
            max_daily_jobs=2,
            working_hours_start="07:00",
            working_hours_end="15:00",
            ai_tone_preference="authoritative",
            verification_level="gold",
            reputation_score=4.7,
            availability_status="Busy",
        ),
        # Global test contractors
        User(
            email="ade@lagosplumbing.ng",
            hashed_password=default_password,
            role="contractor",
            full_name="Ade's Plumbing Services",
            phone="+234-801-234-5678",
            country="Nigeria",
            state_or_province="Lagos",
            city="Lagos",
            area="Ikeja",
            postal_code="100001",
            latitude=6.6000,
            longitude=3.3500,
            profession="plumber",
            service_radius_miles=25,
            base_pricing=15000.0,
            max_daily_jobs=5,
            working_hours_start="08:00",
            working_hours_end="18:00",
            ai_tone_preference="friendly",
            verification_level="gold",
            reputation_score=4.7,
            availability_status="Available",
        ),
        User(
            email="chidi@lagoselectric.ng",
            hashed_password=default_password,
            role="contractor",
            full_name="Chidi Electric Solutions",
            phone="+234-802-345-6789",
            country="Nigeria",
            state_or_province="Lagos",
            city="Lagos",
            area="Lekki",
            postal_code="101001",
            latitude=6.4478,
            longitude=3.4564,
            profession="electrician",
            service_radius_miles=30,
            base_pricing=20000.0,
            max_daily_jobs=4,
            working_hours_start="07:00",
            working_hours_end="19:00",
            ai_tone_preference="professional",
            verification_level="silver",
            reputation_score=4.4,
            availability_status="Available",
        ),
        User(
            email="james@londonplumbing.co.uk",
            hashed_password=default_password,
            role="contractor",
            full_name="James & Sons Plumbing",
            phone="+44-20-7946-0958",
            country="United Kingdom",
            state_or_province="England",
            city="London",
            area="Westminster",
            postal_code="SW1A 1AA",
            latitude=51.5014,
            longitude=-0.1419,
            profession="plumber",
            service_radius_miles=20,
            base_pricing=85.0,
            max_daily_jobs=6,
            working_hours_start="08:00",
            working_hours_end="17:00",
            ai_tone_preference="professional",
            verification_level="verified pro",
            reputation_score=4.9,
            availability_status="Available",
        ),
        User(
            email="priya@newdelhihomes.in",
            hashed_password=default_password,
            role="contractor",
            full_name="Priya Home Services",
            phone="+91-11-2345-6789",
            country="India",
            state_or_province="Delhi",
            city="New Delhi",
            area="Connaught Place",
            postal_code="110001",
            latitude=28.6315,
            longitude=77.2167,
            profession="cleaner",
            service_radius_miles=15,
            base_pricing=500.0,
            max_daily_jobs=4,
            working_hours_start="09:00",
            working_hours_end="18:00",
            ai_tone_preference="warm and professional",
            verification_level="bronze",
            reputation_score=4.3,
            availability_status="Available",
        ),
    ]
    
    customers = [
        User(
            email="john.doe@example.com",
            hashed_password=default_password,
            role="customer",
            full_name="John Doe",
            phone="555-0201",
            zip_code="90210",
            country="United States",
            state_or_province="California",
            city="Beverly Hills",
            area="Beverly Hills",
            postal_code="90210",
            latitude=34.0736,
            longitude=-118.4004,
        ),
        User(
            email="jane.smith@example.com",
            hashed_password=default_password,
            role="customer",
            full_name="Jane Smith",
            phone="555-0202",
            zip_code="90211",
            country="United States",
            state_or_province="California",
            city="Beverly Hills",
            area="West Hollywood",
            postal_code="90211",
            latitude=34.0907,
            longitude=-118.3766,
        ),
        User(
            email="fatima@lagoscustomer.ng",
            hashed_password=default_password,
            role="customer",
            full_name="Fatima Abubakar",
            phone="+234-803-456-7890",
            country="Nigeria",
            state_or_province="Lagos",
            city="Lagos",
            area="Ikeja",
            postal_code="100001",
            latitude=6.6000,
            longitude=3.3500,
        ),
        User(
            email="admin@servicesync.com",
            hashed_password=default_password,
            role="admin",
            full_name="System Admin",
        )
    ]
    
    all_users = contractors + customers
    
    async with async_session_maker() as db:
        from sqlmodel import select
        
        added = 0
        for user in all_users:
            # Check if user exists
            existing = await db.exec(select(User).where(User.email == user.email))
            if not existing.first():
                db.add(user)
                added += 1
                
        if added > 0:
            await db.commit()
            print(f"Successfully seeded {added} users!")
        else:
            print("Database already seeded with these users.")

if __name__ == "__main__":
    asyncio.run(seed_db())
